#!/bin/sh
set -eu

unformatted=$(gofmt -l cmd internal)
if [ -n "$unformatted" ]; then
	printf '%s\n' 'Go files need formatting:' >&2
	printf '%s\n' "$unformatted" >&2
	exit 1
fi

go vet ./...
go test ./...
sh -n website/install.sh
sh scripts/test-installer
