package command

import "fmt"

// Registry contains only runnable operations. Future command ideas stay out of
// discovery until the provider implementation exists, so humans and agents can
// trust this catalog as an executable contract.
var Registry = []Definition{
	{Effect: Observe, Path: []string{"tailscale", "device", "list"}, Summary: "List devices in the configured tailnet.", Notes: nil, Response: "A compact collection of device records.", Options: []Option{{Name: "--tag", Value: "TAG", Description: "Return only devices currently carrying TAG, for example tag:github.", Optional: true}, {Name: "--details", Description: "Include name, owner, addresses, tags, authorization, client version, and key expiry.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "device", "get"}, Summary: "Read one device.", Notes: nil, Response: "One compact device record.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}}, Options: []Option{{Name: "--details", Description: "Include addresses, client version, expiry, and node ID.", Optional: true}}, Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "device", "route", "list"}, Summary: "List a device's subnet and exit-node routes.", Notes: nil, Response: "A collection of route records.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}}, Cardinality: Many, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "device", "retirement", "preflight"}, Summary: "Collect dependency evidence before deleting one device.", Notes: []string{"Read the exact device, its advertised and enabled routes, and active ACL previews for each device tag. This requires devices:core:read, devices:routes:read, and the ACL read scopes documented for Tailscale. Missing evidence is reported explicitly and makes the preflight incomplete; no state is changed."}, Response: "A structured retirement preflight with device posture, routes, tag-policy dependencies, consequences, evidence completeness, and operator-acknowledgement requirements.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Update, Path: []string{"tailscale", "device", "name", "set"}, Summary: "Set a device name.", Notes: []string{"Rename DEVICE_ID to NAME. This changes device metadata but not its access policy."}, Response: "Confirmation of the requested device name.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}, {Name: "NAME", Description: "New device name.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Record the current name with device get, then run the same name set command with that prior value.", Credentials: "tailscale", UnattendedOK: false},
	{Effect: Authorize, Path: []string{"tailscale", "device", "tag", "set"}, Summary: "Replace a device's tag set.", Notes: []string{"Replace all tags on DEVICE_ID with TAG values. Tags affect device identity and tailnet ACLs, so this is an authorization operation."}, Response: "Confirmation of the requested tag set.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}, {Name: "TAG", Description: "One or more tag:NAME values that replace the current tag set.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Record the current tags with device get, then run the same tag set command with that exact prior tag set.", Credentials: "tailscale", UnattendedOK: false},
	{Effect: Authorize, Path: []string{"tailscale", "device", "authorization", "set"}, Summary: "Approve or deauthorize a device.", Notes: []string{"Set whether DEVICE_ID may join a tailnet that requires device approval. This is separate from installing Tailscale and running tailscale up on the host."}, Response: "Confirmation of the requested device authorization state.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}}, Options: []Option{{Name: "--state", Value: "authorized|unauthorized", Description: "Required device authorization state.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run the same command with the prior authorization state reported by observe tailscale device get --details.", Credentials: "tailscale", UnattendedOK: false},
	{Effect: Update, Path: []string{"tailscale", "device", "key", "expiry", "set"}, Summary: "Enable or disable scheduled key expiry for a device.", Notes: []string{"Disabling expiry preserves the original expiry time. Re-enabling it may immediately expire an overdue device and require host re-authentication."}, Response: "Confirmation of the requested key-expiry policy.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}}, Options: []Option{{Name: "--state", Value: "enabled|disabled", Description: "Required key-expiry state.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run the same command with the prior expiry state reported by observe tailscale device get --details.", Credentials: "tailscale", UnattendedOK: false},
	{Effect: Administer, Path: []string{"tailscale", "device", "key", "expire"}, Summary: "Immediately expire a device key.", Notes: []string{"The device immediately loses tailnet connectivity and must be re-authenticated on the host. This cannot be undone through the control-plane API."}, Response: "Confirmation that the device key was expired.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "tailscale", UnattendedOK: false},
	{Effect: Delete, Path: []string{"tailscale", "device", "delete"}, Summary: "Permanently remove a device from the tailnet.", Notes: []string{"The device must belong to the tailnet and will need to run tailscale up again to re-enroll. Shared-in devices cannot be deleted with this endpoint."}, Response: "Deletion confirmation containing the device ID.", Arguments: []Argument{{Name: "DEVICE_ID", Description: "Tailscale device ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "tailscale", UnattendedOK: false},
	{Effect: Observe, Path: []string{"tailscale", "acl", "get"}, Summary: "Download the tailnet ACL into a local file.", Notes: []string{"Write the HuJSON ACL to a new 0600 file. It is never printed to stdout and never overwrites an existing file."}, Response: "The path of the downloaded ACL file and its ETag when supplied.", Options: []Option{{Name: "--output", Value: "PATH", Description: "New destination file; defaults to a timestamped acl.hujson file in the current directory.", Optional: true}}, Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "acl", "validate"}, Summary: "Validate a proposed tailnet ACL without applying it.", Notes: []string{"Send ACL_FILE to Tailscale's validation endpoint. The active ACL is not changed; policy tests in the file are evaluated when present. A rejected ACL returns a nonzero exit status."}, Response: "A stable valid or invalid status and Tailscale's validation result.", Arguments: []Argument{{Name: "ACL_FILE", Description: "Path to a HuJSON tailnet ACL file to validate.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "acl", "preview"}, Summary: "Show ACL rules that match one source identity.", Notes: []string{"Preview the active ACL for SOURCE, or a candidate ACL supplied with --file, without applying any change. SOURCE can be a user or a tag such as tag:github."}, Response: "The matching rules, destinations, and relevant posture conditions.", Options: []Option{{Name: "--for", Value: "SOURCE", Description: "User or tag identity to preview, for example tag:github.", Optional: false}, {Name: "--file", Value: "ACL_FILE", Description: "Candidate HuJSON ACL file; defaults to the active tailnet ACL.", Optional: true}}, Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Administer, Path: []string{"tailscale", "acl", "set"}, Summary: "Replace the tailnet ACL from a local file with a required backup.", Notes: []string{"Validate ACL_FILE, write the current HuJSON ACL to a new private BACKUP_FILE, then replace it only if its ETag is still current. The backup can be used to undo the change."}, Response: "Confirmation with the backup path and ETag used for the guarded replacement.", Arguments: []Argument{{Name: "ACL_FILE", Description: "Path to a HuJSON tailnet ACL file.", Optional: false}}, Options: []Option{{Name: "--backup", Value: "BACKUP_FILE", Description: "Required new path for a 0600 snapshot of the current ACL; Omni never overwrites it.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "The required pre-change backup can be supplied to a later guarded acl set operation; Omni has no separate revert command.", Credentials: "tailscale", UnattendedOK: false},
	{Effect: Observe, Path: []string{"tailscale", "key", "list"}, Summary: "List accessible active Tailscale key metadata.", Notes: []string{"Return active key IDs and non-secret metadata, including key type, scopes, tags, expiry, status, and auth-key creation properties when available. Use --all to broaden active key types visible to the credential. It never returns key material."}, Response: "A collection of compact active key metadata records.", Options: []Option{{Name: "--all", Description: "Request all visible active key types; the provider does not enumerate revoked keys in list results.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "key", "get"}, Summary: "Read non-secret metadata for one Tailscale key.", Notes: []string{"Return key type, scopes, tags, expiry, and invalid or revoked state for KEY_ID when the credential is authorized to read it. It never returns key material."}, Response: "One compact key metadata record.", Arguments: []Argument{{Name: "KEY_ID", Description: "Tailscale control-plane key ID, for example k...CNTRL.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "credential", "get"}, Summary: "Inspect the effective Tailscale authentication without revealing secrets.", Notes: []string{"Report the selected API-token or OAuth-client path, logical configuration sources, OAuth client identity and remote scope metadata when readable, and cached token expiry. API access-token permissions follow their owning user and cannot be enumerated from the local secret."}, Response: "A non-secret effective credential report.", Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Create, Path: []string{"tailscale", "key", "auth", "create"}, Summary: "Create a machine auth key for host enrollment.", Notes: []string{"The one-time secret is written only to a new 0600 OUTPUT file and is never printed. With OAuth credentials, at least one permitted tag is normally required."}, Response: "Non-secret key metadata and the local secret-file path.", Options: []Option{{Name: "--output", Value: "FILE", Description: "Required new file that receives the one-time auth-key secret.", Optional: false}, {Name: "--description", Value: "TEXT", Description: "Purpose of the key, up to the provider limit.", Optional: true}, {Name: "--expiry-seconds", Value: "SECONDS", Description: "Positive lifetime in seconds; defaults to the provider setting.", Optional: true}, {Name: "--tag", Value: "TAG", Description: "Device tag; repeat for more tags.", Optional: true}, {Name: "--reusable", Description: "Allow the key to enroll more than one device.", Optional: true}, {Name: "--ephemeral", Description: "Make enrolled devices ephemeral.", Optional: true}, {Name: "--preauthorized", Description: "Enroll devices without a separate approval step.", Optional: true}}, Cardinality: One, Reversible: true, Reversal: "Run delete tailscale key revoke with the returned key ID; already-enrolled devices remain in the tailnet.", Credentials: "tailscale", UnattendedOK: false},
	{Effect: Delete, Path: []string{"tailscale", "key", "revoke"}, Summary: "Revoke a Tailscale key or trust credential.", Notes: []string{"Revocation prevents future use but does not remove devices that were already enrolled with an auth key."}, Response: "Revocation confirmation containing the key ID.", Arguments: []Argument{{Name: "KEY_ID", Description: "Tailscale control-plane key ID, for example k...CNTRL.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "tailscale", UnattendedOK: false},
	{Effect: Observe, Path: []string{"tailscale", "dns", "get"}, Summary: "Read tailnet DNS configuration.", Notes: nil, Response: "A compact snapshot of tailnet DNS settings.", Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "user", "list"}, Summary: "List users in the configured tailnet.", Notes: nil, Response: "A collection of compact user records.", Cardinality: Many, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"tailscale", "user", "get"}, Summary: "Read one user.", Notes: nil, Response: "One compact user record.", Arguments: []Argument{{Name: "USER_ID", Description: "Tailscale user ID.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "tailscale", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "board", "list"}, Summary: "List boards visible to the configured Trello user.", Notes: nil, Response: "A collection of board IDs and names.", Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "board", "overview"}, Summary: "Read a board and its lists.", Notes: nil, Response: "A board record and collection of list IDs and names.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID. Optional when trello.default-board-id is configured.", Optional: true}}, Cardinality: One, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "list", "list"}, Summary: "List the lists on one board.", Notes: nil, Response: "A collection of list IDs and names.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID. Optional when trello.default-board-id is configured.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "card", "list"}, Summary: "List the open cards in one list.", Notes: nil, Response: "A collection of compact Trello card records.", Arguments: []Argument{{Name: "LIST_ID", Description: "Trello list ID.", Optional: false}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "card", "get"}, Summary: "Read one compact Trello card.", Notes: nil, Response: "One compact Trello card record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "attachment", "list"}, Summary: "List attachments on one card.", Notes: []string{"Use this when a card's badges.attachments count is nonzero."}, Response: "A collection of compact attachment records with IDs, names, URLs, media types, and sizes.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "attachment", "download"}, Summary: "Download one uploaded attachment to a new local file.", Notes: []string{"Requires --output FILE, refuses to overwrite it, and only downloads Trello-hosted uploaded attachments up to 25 MiB."}, Response: "Confirmation containing the attachment ID, local file path, media type, and byte count.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}, {Name: "ATTACHMENT_ID", Description: "Trello attachment ID.", Optional: false}}, Options: []Option{{Name: "--output", Value: "FILE", Description: "New local destination file.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "card", "get-many"}, Summary: "Read up to ten compact Trello cards.", Notes: nil, Response: "A collection of compact Trello card records.", Arguments: []Argument{{Name: "CARD_ID", Description: "One to ten Trello card IDs.", Optional: false, Variadic: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "card", "review"}, Summary: "Read one card with its compact comments.", Notes: nil, Response: "One compact card record and bounded comments with reactions.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "card", "search"}, Summary: "Search card names and descriptions on one board.", Notes: []string{"Use label:NAME to find cards with one board label by name."}, Response: "A bounded collection of compact matching cards and their list identities.", Arguments: []Argument{{Name: "QUERY", Description: "Case-insensitive card text, or label:NAME for one label.", Optional: false}}, Options: []Option{{Name: "--board", Value: "BOARD_ID", Description: "Board to search; defaults to trello.default-board-id.", Optional: true}, {Name: "--limit", Value: "COUNT", Description: "Maximum matching cards to return; defaults to 20.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "checklist", "list"}, Summary: "List a card's checklists and items.", Notes: nil, Response: "A collection of compact Trello checklists.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "checklist", "get"}, Summary: "Read one checklist and its items.", Notes: nil, Response: "One compact Trello checklist record.", Arguments: []Argument{{Name: "CHECKLIST_ID", Description: "Trello checklist ID.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "comment", "list"}, Summary: "List comments and their reactions on one card.", Notes: nil, Response: "A bounded collection of compact Trello comments with reactions.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Options: []Option{{Name: "--limit", Value: "COUNT", Description: "Maximum comments to return; defaults to 20.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "label", "list"}, Summary: "List labels on one board.", Notes: nil, Response: "A collection of compact Trello labels.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID. Optional when trello.default-board-id is configured.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "member", "list"}, Summary: "List members on one board.", Notes: nil, Response: "A collection of compact Trello members.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID. Optional when trello.default-board-id is configured.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "member", "get"}, Summary: "Read one Trello member.", Notes: nil, Response: "One compact Trello member record.", Arguments: []Argument{{Name: "MEMBER_ID", Description: "Trello member ID.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "list", "overview"}, Summary: "Read one list and its compact cards.", Notes: nil, Response: "One compact list record and its compact cards.", Arguments: []Argument{{Name: "LIST_ID", Description: "Trello list ID.", Optional: false}}, Cardinality: One, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "board", "activity", "list"}, Summary: "List recent activity on one board.", Notes: []string{"For commentCard entries, the activity ID is the comment ID accepted by comment reaction create."}, Response: "A bounded collection of compact Trello activity records.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID. Optional when trello.default-board-id is configured.", Optional: true}}, Options: []Option{{Name: "--limit", Value: "COUNT", Description: "Maximum activity records to return; defaults to 20.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Observe, Path: []string{"trello", "card", "activity", "list"}, Summary: "List recent activity on one card.", Notes: nil, Response: "A bounded collection of compact Trello activity records.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Options: []Option{{Name: "--limit", Value: "COUNT", Description: "Maximum activity records to return; defaults to 20.", Optional: true}}, Cardinality: Many, Reversible: true, Credentials: "trello", UnattendedOK: true},
	{Effect: Create, Path: []string{"trello", "card", "create"}, Summary: "Create one Trello card.", Notes: []string{"LIST_ID must be open. Labels and members are included atomically in the initial Trello card request."}, Response: "The created Trello card record.", Arguments: []Argument{{Name: "LIST_ID", Description: "Trello list ID that receives the card.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "Card title.", Optional: false}, {Name: "--description", Value: "TEXT", Description: "Card description.", Optional: true}, {Name: "--due", Value: "DATE", Description: "Card due date accepted by Trello.", Optional: true}, {Name: "--label", Value: "LABEL_ID", Description: "Initial label ID; repeat for more labels.", Optional: true}, {Name: "--member", Value: "MEMBER_ID", Description: "Initial member ID; repeat for more members.", Optional: true}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Create, Path: []string{"trello", "attachment", "upload"}, Summary: "Upload one local file to an open card.", Notes: []string{"FILE must be a regular file no larger than 25 MiB."}, Response: "The created compact Trello attachment record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}}, Options: []Option{{Name: "--file", Value: "FILE", Description: "Regular local file to upload.", Optional: false}, {Name: "--name", Value: "NAME", Description: "Optional attachment name; defaults to the file name.", Optional: true}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Create, Path: []string{"trello", "list", "create"}, Summary: "Create one Trello list.", Notes: nil, Response: "The created compact Trello list record.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "List name.", Optional: false}, {Name: "--position", Value: "POSITION", Description: "Position; defaults to bottom.", Optional: true}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Create, Path: []string{"trello", "comment", "create"}, Summary: "Add one comment to a card.", Notes: nil, Response: "The created compact Trello comment.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}}, Options: []Option{{Name: "--text", Value: "TEXT", Description: "Comment text.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Create, Path: []string{"trello", "label", "create"}, Summary: "Create one label on a board.", Notes: []string{"The label is not attached to a card automatically; use card label add after creation."}, Response: "The created compact Trello label.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "Label name.", Optional: false}, {Name: "--color", Value: "COLOR", Description: "Trello label color.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Create, Path: []string{"trello", "checklist", "create"}, Summary: "Create one checklist on an open card.", Notes: nil, Response: "The created compact Trello checklist record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "Checklist name.", Optional: false}, {Name: "--position", Value: "POSITION", Description: "Position; defaults to bottom.", Optional: true}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Create, Path: []string{"trello", "checklist", "item", "create"}, Summary: "Create one checklist item.", Notes: []string{"The new item begins incomplete; set its position only when ordering matters."}, Response: "The created compact Trello checklist item.", Arguments: []Argument{{Name: "CHECKLIST_ID", Description: "Trello checklist ID.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "Item text.", Optional: false}, {Name: "--position", Value: "POSITION", Description: "Position; defaults to bottom.", Optional: true}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Create, Path: []string{"trello", "comment", "reaction", "create"}, Summary: "Add one reaction to a comment.", Notes: nil, Response: "The created Trello reaction record and its comment ID.", Arguments: []Argument{{Name: "COMMENT_ID", Description: "Trello comment action ID.", Optional: false}}, Options: []Option{{Name: "--emoji", Value: "EMOJI", Description: "Reaction emoji.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run delete trello comment reaction delete with the returned reaction ID.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "set"}, Summary: "Update one open Trello card.", Notes: []string{"Requires at least one update option."}, Response: "The updated compact Trello card record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "New card title.", Optional: true}, {Name: "--description", Value: "TEXT", Description: "New card description.", Optional: true}, {Name: "--due", Value: "DATE", Description: "New due date accepted by Trello.", Optional: true}}, Cardinality: One, Reversible: true, Reversal: "Record the current card with card get, then set its prior field values.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "board", "set"}, Summary: "Update a board description.", Notes: []string{"BOARD_ID is optional when trello.default-board-id is configured."}, Response: "The updated compact Trello board record.", Arguments: []Argument{{Name: "BOARD_ID", Description: "Trello board ID. Optional when trello.default-board-id is configured.", Optional: true}}, Options: []Option{{Name: "--description", Value: "TEXT", Description: "Replacement board description.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Record the current description with board overview, then set that prior value.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "due", "complete", "set"}, Summary: "Set one open card's due-date completion state.", Notes: []string{"This changes dueComplete without changing the due date itself."}, Response: "The updated compact Trello card record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}}, Options: []Option{{Name: "--state", Value: "complete|incomplete", Description: "Required due-date completion state.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run the same command with the opposite state.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "unarchive"}, Summary: "Unarchive one Trello card.", Notes: []string{"Restores CARD_ID to an open workflow state so normal card mutations are allowed again."}, Response: "The reopened compact Trello card record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Archived Trello card ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run archive trello card archive CARD_ID.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "list", "name", "set"}, Summary: "Rename one Trello list.", Notes: []string{"LIST_ID must be open; archived lists must be unarchived before their metadata changes."}, Response: "The updated compact Trello list record.", Arguments: []Argument{{Name: "LIST_ID", Description: "Trello list ID.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "New list name.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Record the current name with list list, then set that prior value.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "list", "unarchive"}, Summary: "Unarchive one Trello list.", Notes: []string{"Restores LIST_ID so it can receive cards and its metadata can be changed again."}, Response: "The reopened compact Trello list record.", Arguments: []Argument{{Name: "LIST_ID", Description: "Archived Trello list ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run archive trello list archive LIST_ID.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "checklist", "item", "set"}, Summary: "Set one checklist item's completion state.", Notes: nil, Response: "The updated compact Trello checklist item.", Arguments: []Argument{{Name: "CHECKLIST_ID", Description: "Trello checklist ID.", Optional: false}, {Name: "ITEM_ID", Description: "Trello checklist item ID.", Optional: false}}, Options: []Option{{Name: "--state", Value: "complete|incomplete", Description: "Required completion state.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run the same command with the opposite state.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "checklist", "item", "name", "set"}, Summary: "Rename one checklist item.", Notes: nil, Response: "The updated compact Trello checklist item.", Arguments: []Argument{{Name: "CHECKLIST_ID", Description: "Trello checklist ID.", Optional: false}, {Name: "ITEM_ID", Description: "Trello checklist item ID.", Optional: false}}, Options: []Option{{Name: "--name", Value: "NAME", Description: "Replacement checklist-item text.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Record the current item text with checklist get, then set that prior value.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "label", "add"}, Summary: "Add one label to an open card.", Notes: nil, Response: "Confirmation of the label attachment.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}, {Name: "LABEL_ID", Description: "Trello label ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run update trello card label remove with the same IDs.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "label", "remove"}, Summary: "Remove one label from an open card.", Notes: nil, Response: "Confirmation of the label removal.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}, {Name: "LABEL_ID", Description: "Trello label ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run update trello card label add with the same IDs.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "member", "add"}, Summary: "Assign one member to an open card.", Notes: nil, Response: "Confirmation of the member assignment.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}, {Name: "MEMBER_ID", Description: "Trello member ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run update trello card member remove with the same IDs.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "member", "add-many"}, Summary: "Assign multiple members to an open card.", Notes: []string{"Each member is assigned independently; a later provider error may leave earlier assignments applied."}, Response: "Confirmation containing the assigned member IDs.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}, {Name: "MEMBER_ID", Description: "One or more Trello member IDs.", Optional: false, Variadic: true}}, Cardinality: Many, Reversible: true, Reversal: "Run update trello card member remove once for each assigned member ID.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "card", "member", "remove"}, Summary: "Unassign one member from an open card.", Notes: nil, Response: "Confirmation of the member removal.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}, {Name: "MEMBER_ID", Description: "Trello member ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run update trello card member add with the same IDs.", Credentials: "trello", UnattendedOK: false},
	{Effect: Update, Path: []string{"trello", "comment", "set"}, Summary: "Edit one Trello comment.", Notes: nil, Response: "The updated compact Trello comment.", Arguments: []Argument{{Name: "COMMENT_ID", Description: "Trello comment action ID.", Optional: false}}, Options: []Option{{Name: "--text", Value: "TEXT", Description: "Replacement comment text.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Record the prior comment text with comment list, then set that prior text.", Credentials: "trello", UnattendedOK: false},
	{Effect: Move, Path: []string{"trello", "card", "move"}, Summary: "Move one open Trello card to a list or position.", Notes: []string{"Both CARD_ID and LIST_ID must be open; unarchive either before moving the card."}, Response: "The updated Trello card record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}, {Name: "LIST_ID", Description: "Destination Trello list ID.", Optional: false}}, Options: []Option{{Name: "--position", Value: "POSITION", Description: "Destination position; defaults to bottom.", Optional: true}}, Cardinality: One, Reversible: true, Reversal: "Record the prior list and position, then run the same move command with those prior values.", Credentials: "trello", UnattendedOK: false},
	{Effect: Move, Path: []string{"trello", "list", "move"}, Summary: "Move one Trello list to a position.", Notes: []string{"LIST_ID must be open."}, Response: "The updated compact Trello list record.", Arguments: []Argument{{Name: "LIST_ID", Description: "Trello list ID.", Optional: false}}, Options: []Option{{Name: "--position", Value: "POSITION", Description: "Required destination position.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Record the current position with list overview, then run the same move command with that value.", Credentials: "trello", UnattendedOK: false},
	{Effect: Archive, Path: []string{"trello", "card", "archive"}, Summary: "Archive one Trello card.", Notes: []string{"Close one card while preserving it in Trello's archive."}, Response: "The archived Trello card record.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run update trello card unarchive CARD_ID.", Credentials: "trello", UnattendedOK: false},
	{Effect: Archive, Path: []string{"trello", "list", "archive"}, Summary: "Archive one Trello list.", Notes: []string{"Close LIST_ID while preserving it in Trello's archive."}, Response: "The archived compact Trello list record.", Arguments: []Argument{{Name: "LIST_ID", Description: "Trello list ID.", Optional: false}}, Cardinality: One, Reversible: true, Reversal: "Run update trello list unarchive LIST_ID.", Credentials: "trello", UnattendedOK: false},
	{Effect: Archive, Path: []string{"trello", "list", "cards", "archive"}, Summary: "Archive all open cards in one list.", Notes: []string{"Archive every open card currently in LIST_ID. This does not archive the list itself."}, Response: "The archived card IDs and count.", Arguments: []Argument{{Name: "LIST_ID", Description: "Trello list ID.", Optional: false}}, Cardinality: Many, Reversible: true, Reversal: "Run update trello card unarchive for each archived_card_ids value returned by this command.", Credentials: "trello", UnattendedOK: false},
	{Effect: Delete, Path: []string{"trello", "checklist", "item", "delete"}, Summary: "Permanently delete one checklist item.", Notes: []string{"This discards the item's text and completion history; mark it incomplete instead when preserving the work record matters."}, Response: "Deletion confirmation containing the item ID.", Arguments: []Argument{{Name: "CHECKLIST_ID", Description: "Trello checklist ID.", Optional: false}, {Name: "ITEM_ID", Description: "Trello checklist item ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Delete, Path: []string{"trello", "attachment", "delete"}, Summary: "Permanently delete one attachment from a card.", Notes: []string{"This removes the remote attachment; download it first when a local copy is needed."}, Response: "Deletion confirmation containing the attachment ID.", Arguments: []Argument{{Name: "CARD_ID", Description: "Open Trello card ID.", Optional: false}, {Name: "ATTACHMENT_ID", Description: "Trello attachment ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Delete, Path: []string{"trello", "checklist", "delete"}, Summary: "Permanently delete one checklist.", Notes: []string{"This also discards its items and their completion history."}, Response: "Deletion confirmation containing the checklist ID.", Arguments: []Argument{{Name: "CHECKLIST_ID", Description: "Trello checklist ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Delete, Path: []string{"trello", "comment", "reaction", "delete"}, Summary: "Remove one reaction from a comment.", Notes: []string{"Use the reaction ID returned by reaction create or listed in a comment's reactions; the comment itself remains unchanged."}, Response: "Deletion confirmation containing the reaction ID.", Arguments: []Argument{{Name: "COMMENT_ID", Description: "Trello comment action ID.", Optional: false}, {Name: "REACTION_ID", Description: "Trello reaction ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Delete, Path: []string{"trello", "comment", "delete"}, Summary: "Permanently delete one Trello comment.", Notes: []string{"Use comment set when the text should be corrected rather than removed."}, Response: "Deletion confirmation containing the comment ID.", Arguments: []Argument{{Name: "COMMENT_ID", Description: "Trello comment action ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Delete, Path: []string{"trello", "card", "delete"}, Summary: "Permanently delete one Trello card.", Notes: []string{"Use archive instead when the card may need to be restored later."}, Response: "Deletion confirmation containing the card ID.", Arguments: []Argument{{Name: "CARD_ID", Description: "Trello card ID.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
	{Effect: Delete, Path: []string{"trello", "label", "delete"}, Summary: "Permanently delete one board label.", Notes: []string{"Trello removes the label from every card on its board, so this is broader than one card. Use update trello card label remove when only one card should lose the label.", "Omni reads the label before deleting it and reports its board, name, and color so an equivalent label can be recreated deliberately. Recreated labels get a new ID and are not reattached to any card."}, Response: "Deletion confirmation containing the deleted label's ID, board ID, name, and color.", Arguments: []Argument{{Name: "LABEL_ID", Description: "Trello label ID, as reported by observe trello label list.", Optional: false}}, Cardinality: One, Reversible: false, Credentials: "trello", UnattendedOK: false},
}

func Find(tokens []string) (Definition, error) {
	for _, d := range Registry {
		if same(d.Tokens(), tokens) {
			return d, nil
		}
	}
	return Definition{}, fmt.Errorf("unknown command %q", join(tokens))
}

// Match finds a complete command path at the left of tokens and returns the
// remaining resource identifiers and values. Those remaining arguments cannot
// alter the effect because the definition has already been selected.
func Match(tokens []string) (Definition, []string, error) {
	for _, d := range Registry {
		path := d.Tokens()
		if len(tokens) < len(path) || !same(path, tokens[:len(path)]) {
			continue
		}
		return d, tokens[len(path):], nil
	}
	return Definition{}, nil, fmt.Errorf("unknown command %q", join(tokens))
}

func same(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
func join(s []string) string {
	if len(s) == 0 {
		return ""
	}
	r := s[0]
	for _, v := range s[1:] {
		r += " " + v
	}
	return r
}

func init() {
	for _, d := range Registry {
		if err := d.Validate(); err != nil {
			panic(err)
		}
	}
}
